version: '2'

services:
  postgres:
    image: 'mdillon/postgis:latest'
    env_file:
      - '.env'
    volumes:
      - 'postgres:/var/lib/postgresql/data'
    ports:
      - '5432:5432'

  api:
    build: ./
    command: gunicorn -c gunicorn.py --reload "magicride:create_app()"
    env_file:
      - '.env'
    volumes:
      - '.:/magicride'
    ports:
        - '8000:8000'
    depends_on:
      - postgres

volumes:
  postgres:
